version: '3'
services:
  web:
    image: nginx:alpine
    container_name: nginxPB
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/log/nginx:/var/log/nginx/"
      - "./app/:/var/www/phonebook"
    ports:
      - "89:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    depends_on:
      - php
      - mysqldb
  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    container_name: phpPB
    restart: always
    links:
      - mysqldb
    depends_on:
      - mysqldb
    volumes:
      - "./app/:/var/www/phonebook"
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadminPB
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: mysqlPB
    restart: always
    env_file:
      - .env
#    command: --init-file /docker/sql/init.sql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - "./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./docker/data/mysql:/var/lib/mysql"
